### ISSUE TITLE
How can I help you?

### ISSUE THREAD

**Issue by Bernardstanislas** [xJonathanLEI/oriac#2]
Hi @xJonathanLEI, I'd like to contribute to your project, either to learn Rust and Cairo at the same time. Do you have ideas of good first issues that you could redact to get some external help?

**Comment by xJonathanLEI** [comment]
Hi @Bernardstanislas thanks for reaching out. Unfortunately `oriac` does not accept contributions at the moment. See [this section](https://github.com/xJonathanLEI/oriac/blob/49e8378241b39e567c985c27405966d4a896cb05/README.md#Contributions) on README.
